### ISSUE TITLE
[feat] 회원가입 기능 구현

### ISSUE THREAD

**Issue by nathan29849** [haru-speak/server#19]
## 📝 구현 목록

- [ ] 멤버 회원가입 기능 구현 

<br>

## 💡 참고자료

- (없다면 이 항목을 지워주세요.)

**Comment by jakalroni** [comment]
현재 MemberService의 회원가입 테스트 코드 실행 시 

![image](https://user-images.githubusercontent.com/79403892/213901723-80679434-0a72-48c3-b264-34cd0cd489b3.png)

위와 같은 에러가 발생하는데 

에러로그를 살펴보니 

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource~~~
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate ~~~
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.h2.Driver~~~
```

라고 출력되었는데, 어떤 부분이 문제인지 검색해봐도 잘 모르겠어서 도움을 받으면 좋겠습니다 ㅠㅠ

**Comment by nathan29849** [comment]
현재 테스트를 돌릴 때 어떤 profile로 실행되나요? 
혹시 ${profile}로 실행되지는 않나요??

**Comment by jakalroni** [comment]
테스트를 돌릴 때 어떤 profile로 실행됐는지는 혹시 어디서 확인할 수 있나요?!

![image](https://user-images.githubusercontent.com/79403892/213902040-fa9dcc96-0e0a-4fd2-8f33-1cb311bf09f2.png)

코드 상으론 `@ActiveProfiles("test")` 로 작성하였는데...

**Comment by nathan29849** [comment]
테스트 run에서 확인하실 수 있어요
그리고 지금 test profile은 관련 설정파일이 없기 때문에 안될겁니다
일단은 "local"로 진행해주세요☺️

**Comment by jakalroni** [comment]
![image](https://user-images.githubusercontent.com/79403892/213902155-7588fdd3-d81d-499a-a15e-eae69a6aef94.png)

테스트 run에서 profile 키워드로 검색한 결과, 위처럼 나옵니다!!

그러면 "local"로 진행할려면  `@ActiveProfiles("local")`으로 수정하도 테스트 돌리면 될까요?!

**Comment by nathan29849** [comment]
네 그렇게 해보시고 안되면 다시 말씀해주세요

**Comment by nathan29849** [comment]
네 일단은 local이니까 그래야겠죠??
