### ISSUE TITLE
[common/docs] 스피킹 스터디 ERD 작성하기

### ISSUE THREAD

**Issue by nathan29849** [haru-speak/server#22]
## 📝 구현 목록

- [ ] 스피킹 스터디 화면 부분 ERD 작성하기

**Comment by leeys1218** [comment]
아래 2개의 화면에 대한 스터디 테이블입니다.

![image](https://user-images.githubusercontent.com/95534831/213747608-ba8ac59f-2d93-4abd-9e5d-d03bd7ba9bf4.png)

스터디 테이블, 멤버와의 조인 테이블, 댓글과 좋아요 테이블을 작성했습니다.

"스터디 검색" 이라는 화면의 검색 창 밑에 있는 언어, 레벨 등도 스터디 생성 시 필요한 정보입니다. (팀장과 토의)


![image](https://user-images.githubusercontent.com/95534831/213751318-83664a90-3962-4382-9250-c588c6bd7f6d.png)

- 테이블명을 speaking-study 대신 study로 작성했습니다. 스터디가 목표하는 자격증이 있고, 대면 활동이 있다는 것을 고려할 때 speaking 이라는 키워드를 빼는 것이 더 자연스럽다고 생각하기 때문입니다.
- VARCHAR 타입을 가지는 값의 크기를 임의로 정하였습니다. 구글링과 주관적으로 적당하다고 생각하는 수준으로 설정하였습니다.

위 두 고려 사항에 대한 의견이나 테이블에 수정 사항이 있는지 피드백 주시면 감사하겠습니다!

**Comment by leeys1218** [comment]
-

**Comment by leeys1218** [comment]
내스터디 화면의 과제 탭에 대한 과제 테이블입니다.

![image](https://user-images.githubusercontent.com/95534831/213752483-7ddcb3a8-839d-4d86-884f-6d9aa2304d1c.png)



하나의 스터디가 여러 과제를 가질 수 있어 1(스터디) : N(과제)  과제 테이블을, 

하나의 과제가 여러 멤버를, 하나의 멤버가 여러 과제를 가질 수 있어 다대다로 멤버 - 과제 테이블을 설계하였습니다.


![image](https://user-images.githubusercontent.com/95534831/213754015-7e6e235d-8cde-4e7c-bf61-9c3816138d4a.png)

**Comment by leeys1218** [comment]
또한, 아직 스터디 상세설명 페이지와 메세지 화면이 피그마에 작성이 안되어있는데,

- 상세설명 페이지에서 스터디 신청 버튼을 클릭하면 스터디 장에게 디엠을 보낼 수 있는데, 이에 대한 구현과 테이블 설계를 상의해봐야 할 것 같습니다.
- 상세설명 페이지에서 제공되는 추가적인 정보는 스터디 장에게 디엠으로 보내지는 멤버 테이블 정보이므로 (팀장과 토의함) 더 이상 작성할 테이블은 없다고 생각됩니다. 

이에 의견 주시면 감사하겠습니다!!

**Comment by jakalroni** [comment]
명절 준비를 직접 하느라 늦게나마 모바일로 확인하였습니다 ㅠㅠ 
보여주신 피그마 화면에 맞게 적절하게 ERD 설계 해주신 것 같아보여요!

하나 궁금한건 

![image](https://user-images.githubusercontent.com/79403892/213862573-7e79c9a5-63e1-4574-9fa4-a74989e15139.png)

위 사진에서 하트 표시가 

![image](https://user-images.githubusercontent.com/79403892/213862589-b5a8556e-16fe-4c1f-9563-01e7cc259602.png)

'좋아요'의 의미인지 '찜'의 의미인지 잘 모르겠어서 이건 기획자분께 여쭤본 다음에 혹시 '찜'의 의미라면 ERD에 '좋아요'를 '찜' 혹은 '관심'이란 키워드로 변경하면 좋을 것 같습니다!!

**Comment by leeys1218** [comment]
바쁘신 와중에 의견 감사드립니다!

다시보니 찜한 스터디를 고려하지 않고 설계한 것 같아 만들어야 할 것 같습니다.

좋아요 테이블은 아래 화면에 좋아요 개수를 표시하는 화면을 보고 설계했습니다.

![image](https://user-images.githubusercontent.com/95534831/213868098-af030596-c3ff-4ba3-ad67-d7b57c7503c8.png)


말씀하신대로 '찜'과 헷갈릴 수도 있을 것 같아 팀장님께 건의해보겠습니다.

**Comment by HanKwanJin** [comment]
고생하셨습니다 연! 한 가지 건의 사항이 있다면 사진 화질 문제로 테이블 컬럼명들이 흐릿하게 보여서 테이블 사진을 하나씩 크게 해주시면 어떨까 합니다!  그러면 이슈에서도 바로 테이블들을 잘 확인 가능할 것 같아요.

**Comment by leeys1218** [comment]
넵 이슈에서 바로 확인하려면 신경쓰는게 좋은 것 같네요!

**Comment by leeys1218** [comment]
'관심있는 스터디를 찜할 수 있는 기능'에 관한 테이블을 설계하는데 의견을 묻고 싶습니다.

멤버와 스터디 ID를 외래키로 갖는 테이블을 만들어서

'특정 멤버가 찜한 스터디' 관계를 저장해야 할 것 같은데,

![image](https://user-images.githubusercontent.com/95534831/213903551-d8e78b31-915e-4181-865e-361b6ef3c7d4.png)


위의 '특정 멤버가 속해있는 스터디' 테이블과 똑같은 칼럼을 가지는 테이블이 설계될 것 같습니다.



따라서 기존 테이블에  '찜(내가 관심있는)' , '소속(내가 속해있는)'의 의미를 구분 짓는 relationship이라는 칼럼을 추가하여 멤버와 스터디의 관계를 나타내는 테이블을 한개로 관리하는 방법을 생각해봤습니다. 

![image](https://user-images.githubusercontent.com/95534831/213903538-cb72c313-f8ab-42cc-992d-9acf0c6f31ac.png)


하지만 테이블을 하나로 관리하는 대신 column이 추가되어 각 관계를 두 개의 테이블로 관리하는 것보다 용량 소모가 클 것 같다는 생각이 들어 저는 두 개의 테이블로 관리하는 것이 좋다고 생각합니다. 


어느 방식이 좋을까요??

아니면 다른 방식도 있을까요??

**Comment by nathan29849** [comment]
찜 / 소속 여부를 각각 조회할일이 많으면 별도로 관리하는게 조회할때 효율적일 것 같습니다.

**Comment by leeys1218** [comment]
넵 감사합니다.
