### ISSUE TITLE
[common/docs] 스피킹 스터디 및 마이 페이지 관련 API 명세 작성 및 Swagger 적용하기 

### ISSUE THREAD

**Issue by nathan29849** [haru-speak/server#23]
## 📝 구현 목록

- [ ] Notion API 명세 작성하기
- [ ] Swagger를 통해 Mockup API 만들기
  - [ ] 컨트롤러 테스트

**Comment by leeys1218** [comment]
스터디(11개), 스터디-과제(6개) 에 대해 작성해야 할 API의 이름들을 일단 notion에 적어두었습니다. 

마이페이지 화면은 아직 figma에 작성되지 않아서 제공할 정보들을 함께 고민해봐야 할 것 같습니다. 

![image](https://user-images.githubusercontent.com/95534831/213906694-22f7dfc7-68a5-4fb1-90ff-1c10b5be7d33.png)

https://www.notion.so/API-c6195e5c6b2c44cfa9952f394182b8ff

**Comment by nathan29849** [comment]
고생 많으셨습니다!!
