### ISSUE TITLE
[feat] Spring Security Config 설정 및 Member 도메인 구성

### ISSUE THREAD

**Issue by jakalroni** [haru-speak/server#6]
## 📝 구현 목록

- [x] Spring Security Config 설정
- [x] Member 도메인 구성

**Comment by nathan29849** [comment]
너무 이슈 단위가 커버리면 그만큼 커밋이 많이 쌓이게 되고, 되돌리기 힘들거에요
이보다는 조금 더 작은 단위로 이슈를 등록해주시면 좋을 것 같습니다.
예를들어 SpringSecurity Config 설정과 Member 도메인 구성을 묶어서 하나,
회원가입 구현과 회원가입 테스트를 묶어서 하나,
로그인 구현과 로그아웃 구현 및 로그인 & 로그아웃 테스트를 묶어서 하나

이렇게 총 3 파트로 나눌 수 있을 것 같습니다!
