### ISSUE TITLE
Figma 화면에 맞게 Entity 및 DTO 수정 사항 정리

### ISSUE THREAD

**Issue by HanKwanJin** [haru-speak/server#81]
## 🤔 코드 개선 필요성

- 화면 설계가 다 이루어지지 않은 상태에서 작성된 Entity 및 DTO들을 완성된 화면에 맞게 수정되어야 할 것 같습니다.
- 다음 회의에서 논의가 될 수 있도록 아래 리팩토링 목록 부분에 작성해두려합니다. 

### 스터디

- [x] ~목표로 하는 스피킹 시험이 있나요? 부분을 참고해서 자격증(Certificate) 목표(Goal) 두 필드의 이름을 `String speakingTest` `String grade`으로 변경해야 할 것 같습니다. 또한 목표가 없음을 선택할 수 있기에 둘 다 nullable 해야 할 것 같습니다.~
    
<img width="376" alt="image" src="https://user-images.githubusercontent.com/49313910/215493590-72cfbb6f-5b9d-448a-8c4e-dfb87bf4bcb1.png">

![image](https://user-images.githubusercontent.com/49313910/215493761-069c198e-1e8c-4aea-b3fa-fcc928d7b160.png)

- [x] 기존 timePerWeek는 Integer로 받고 있는데 화면 상으로 [월, 화, 수, 목, 금, 토, 일] 을 선택할 수 있게 되어있습니다. 프론트에서 [월 목 금] 을 선택하면 timePerWeek에 월목금이라는 String 형식으로 저장되어서 문자열의 길이가 주 몇회가 될 수 있도록 하는게 어떨까요?

<img width="369" alt="image" src="https://user-images.githubusercontent.com/49313910/215494111-140e583f-642a-4261-867e-cec51359d5e1.png">

![image](https://user-images.githubusercontent.com/49313910/215494187-779d09ec-e1eb-40e5-a84c-c1277a6967fd.png)

- [x] 대면 스터디 방식을 정하는 부분에서 지역을 저장하는 필드가 추가되어야 할 것 같습니다. 비대면일 경우에는 지역 값이 들어오지 않으므로 nullable 해야 할 것 같습니다. 

![image](https://user-images.githubusercontent.com/49313910/215494324-50f1de8a-27ee-4b6e-8d8f-778271beec0d.png)

- [x] ~스터디 인원을 정하는 부분에서 capacity 필드를 최소 인원과 최대 인원을 나타낼 수 있도록 minCapacity, maxCapacity 필드로 나눠서 작성해야 합니다.~

![image](https://user-images.githubusercontent.com/49313910/215811921-ef9bc969-908e-43a1-b123-e86add9b14b7.png)

### 스터디 멤버

- [x] ~StudyMember Entity에 팀장 또는 팀원을 나타내는 필드를 추가해야 할 것 같습니다.~

![image](https://user-images.githubusercontent.com/49313910/215771872-bd5014b2-6ba1-4ed3-824e-fe784d6b991f.png)

![image](https://user-images.githubusercontent.com/49313910/215771903-201d3300-f7b6-4f0a-a2c0-e7ce8f0f49e2.png)

### 스터디룸

- [x] 홈 화면에서 오늘의 문장에 대한 스피킹 로그가 존재하므로 스터디룸에서는 과제에 해당되는 스피킹 로그 테이블을 따로 설계해야 할 것 같습니다. 홈 화면에서 ALL 로 오늘의 문장을 조회했을 때 스피킹 로그 테이블을 하나로 관리하면 스터디 안에서 과제에 대한 스피킹 로그까지 모두 노출이 되어버리기 때문입니다. 

![image](https://user-images.githubusercontent.com/49313910/215503063-ce32162e-48fc-4b96-be65-7e34bf397bb0.png)

### ERD 수정

- [x] 기존 스피킹 로그 테이블은 오늘의 문장의 답변에 사용되는  테이블이였지만,  과제 제출에 사용되는 스피킹 로그를 추가적으로 사용함에 따라 특정 스피킹 로그가 어디에 제출되는 것인지(오늘의 문장, 과제) 구분해야 합니다. 
![image](https://user-images.githubusercontent.com/95534831/215949926-7000b9b4-15f3-4386-86ad-6af6c49675ca.png)  
![image](https://user-images.githubusercontent.com/95534831/215950438-e9fba6ba-59ba-4ac2-97d7-c7de6747750c.png)

### 스터디 상세
- [x] 스터디 상세 조회에서와 스터디룸에서 댓글이 따로 존재하지 않아 `StudyDetailResponse` 에서 댓글 리스트를 제공하는 필드는 제거해야할 것 같습니다.

![image](https://user-images.githubusercontent.com/49313910/216297220-ad08d104-40e6-4d95-88af-c6af1c68dc04.png)

![image](https://user-images.githubusercontent.com/49313910/216297481-be4d063a-32bd-463c-bf9c-07c76a2c8da9.png)

**Comment by leeys1218** [comment]
### 스터디룸 관련 ERD 수정 사항

![image](https://user-images.githubusercontent.com/95534831/215951232-7cf07f81-ee2b-44f8-9a47-dc77e13737d7.png)

- 멤버-주제 테이블로 어떤 멤버가 어떤 주제를 가지고 있는지 조회한 다음 해당하는 오늘의  문장 스피킹 로그를 불러올 수 있습니다.
- 멤버-과제 테이블로 어떤 멤버가  어떤 과제를 가지고 있는지 조회한 다음 해당 멤버가 제출한 스피킹 로그를 불러올 수 있습니다. 

만약 스터디 로그 테이블에 직접 주제, 과제를 구분하는 행을 추가하여 작성한다면, 데이터 중복이 일어날 수 있어  위와 같이  설계하였습니다. 또 다른 방안이 있으시다면 코멘트 부탁드립니다!!

**Comment by nathan29849** [comment]
리뷰 늦어서 죄송합니다! 
제 생각은 아래에 적어두겠습니다! 

### 스터디

- [x] 목표로 하는 스피킹 시험이 있나요? 부분을 참고해서 자격증(Certificate) 목표(Goal) 두 필드의 이름을 `String speakingTest` `String grade`으로 변경해야 할 것 같습니다. 또한 목표가 없음을 선택할 수 있기에 둘 다 nullable 해야 할 것 같습니다.

-> 그렇다면 목표(Goal)라는 도메인을 Grade로 바꾸자는 말씀이신가요??  제 생각에는 목표(Goal) 도메인이 시험 종류와 레벨을 가지고 있게 하는 것은 어떨까해서요!

- [x] 기존 timePerWeek는 Integer로 받고 있는데 화면 상으로 [월, 화, 수, 목, 금, 토, 일] 을 선택할 수 있게 되어있습니다. 프론트에서 [월 목 금] 을 선택하면 timePerWeek에 월목금이라는 String 형식으로 저장되어서 문자열의 길이가 주 몇회가 될 수 있도록 하는게 어떨까요?

-> 월,화,수,목 ~ 에 대한 데이터를 Enum으로 관리하는 것은 어떨까요? 그리고 스터디는 그것을 Set 자료형으로 가지고 있으면 중복 값에 대해 신경쓰지 않아도 될 것 같아서요..! 물론 DB에 저장을 어떻게 할 것인지에 대해서는 논의를 해봐야 할 것 같습니다.

- [x] 대면 스터디 방식을 정하는 부분에서 지역을 저장하는 필드가 추가되어야 할 것 같습니다. 비대면일 경우에는 지역 값이 들어오지 않으므로 nullable 해야 할 것 같습니다. 

-> 지역도 마찬가지로 Enum으로 관리하면 좋을 것 같아요! 일단 지역은 하나만 고를 수 있는 것 같아 위 timePerWeek 보다 DB에 넣는 방식을 생각하긴 쉬울 것 같습니다.

- [x] 스터디 인원을 정하는 부분에서 capacity 필드를 최소 인원과 최대 인원을 나타낼 수 있도록 minCapacity, maxCapacity 필드로 나눠서 작성해야 합니다.
-> 좋은 것 같습니다!

### 스터디 멤버

- [x] StudyMember Entity에 팀장 또는 팀원을 나타내는 필드를 추가해야 할 것 같습니다.
-> 좋은 것 같습니다! `captain` 과 같은 필드로 나타내면 좋겠네요!

### 스터디룸

- [x] 홈 화면에서 오늘의 문장에 대한 스피킹 로그가 존재하므로 스터디룸에서는 과제에 해당되는 스피킹 로그 테이블을 따로 설계해야 할 것 같습니다. 홈 화면에서 ALL 로 오늘의 문장을 조회했을 때 스피킹 로그 테이블을 하나로 관리하면 스터디 안에서 과제에 대한 스피킹 로그까지 모두 노출이 되어버리기 때문입니다. 
-> 좋은 지적 같아요! 다만 스피킹 로그에 과제 필드를 추가해서 관리하는 방법과 아예 과제용 스피킹 로그를 따로 관리하는 부분에 대해서는 함께 논의해보면 좋을 것 같습니다!

### ERD 수정

- [x] 기존 스피킹 로그 테이블은 오늘의 문장의 답변에 사용되는  테이블이였지만,  과제 제출에 사용되는 스피킹 로그를 추가적으로 사용함에 따라 특정 스피킹 로그가 어디에 제출되는 것인지(오늘의 문장, 과제) 구분해야 합니다. 
-> 위에 답변 드린 내용과 같습니다!

**Comment by nathan29849** [comment]
조회가 많을 것 같은 스피킹 로그 종류를 주제용과 오늘의 문장용으로 나눈 결정은 좋아보입니다!

**Comment by leeys1218** [comment]
의견 감사합니다! 말씀하신 과제용 스피킹로그, 일반용 스피킹 로그를 구분하기 위해 스터디룸 관련ERD 코멘트 사진의
과제-스피킹 로그 테이블,
주제-스피킹 로그 테이블 입니다.

위와 같이 설계하면 스피킹 로그 테이블을 하나로 유지하면서 중복을 방지할 수 있을 것 같기 때문입니다. 혹시 제 답변과 말씀하신 의도가 다르다면 재답변 부탁드립니다!

**Comment by nathan29849** [comment]
과제-스피킹 로그 테이블, 주제-스피킹 로그 테이블로 만들어버리면 도메인 객체로 AssignmentSpeakingLog, SubjectSpeakingLog 이렇게 생기게 될텐데, 이 때, 이 도메인 객체가 중간 테이블로써의 역할이 아니라 우리가 현재 가진 SpeakingLog 처럼 아예 그 스피킹 로그들 자체를 나타내야한다는 생각을 했어요
그래서 중간테이블이 아니므로 FK로 각각 과제 ID와 주제 ID를 갖는거구요! 
혹시 이해가 안되시면 말씀해주세요!

**Comment by HanKwanJin** [comment]
### 스터디
- [ ] 목표로 하는 스피킹 시험이 있나요? 부분을 참고해서 자격증(Certificate) 목표(Goal) 두 필드의 이름을 String speakingTest String grade으로 변경해야 할 것 같습니다. 또한 목표가 없음을 선택할 수 있기에 둘 다 nullable 해야 할 것 같습니다.
-> 그렇다면 목표(Goal)라는 도메인을 Grade로 바꾸자는 말씀이신가요?? 제 생각에는 목표(Goal) 도메인이 시험 종류와 레벨을 가지고 있게 하는 것은 어떨까해서요!

-> 아닙니다! 기존에 있던 것은 `String goal`로 도메인 Goal과 다릅니다. 현재 도메인 Goal은 처음 회원 설정을 할 때 5가지 스피킹 목표를 저장하는 부분을 나타냅니다. 그래서 제가 바꾼 부분은 어떤 스피킹 시험인지 저장하는 `String speakingTest` 와 해당 스피킹 테스트의 등급을 저장하는 `String grade`를 두고자 했습니다.

**Comment by nathan29849** [comment]
아하 그런거라면 좋은 생각 같습니다!!

**Comment by leeys1218** [comment]
아 제가 생성되는 도메인 객체를 고려 하지 않았던 것 같습니다 :(

말씀하신대로 수정 하면 중복도 방지하면서 조회시 오버헤드도 줄일 수 있을 것 같습니다!

**Comment by HanKwanJin** [comment]
![image](https://user-images.githubusercontent.com/49313910/216228184-b35f4927-e47c-469b-a9c2-cfc6d158be36.png)

중간 테이블이 아닌 멤버-과제 ID를 FK로 가지는 과제 스피킹 로그를 만들었습니다. 과제는 여러 사람이 같은 과제를 받을 수 있기 때문에 어떤 멤버가 해당 과제를 받고 제출했는지 알아야겠다고 생각되어 멤버-과제 ID 를 FK로 갖도록 하였습니다.

변경할 부분이 있다면 말씀해주세요!

**Comment by nathan29849** [comment]
너무 고생하셨습니다!! 
일반 스피킹 로그도 추가해서 보여주시면 좋을 것 같아요!

**Comment by leeys1218** [comment]
수고하셨습니다!!

**Comment by HanKwanJin** [comment]
### 기존 스피킹 로그
![image](https://user-images.githubusercontent.com/49313910/216231483-3d9d7aaa-9c9a-452b-8e9d-2d0356d7e0fb.png)

### 변경된 스피킹 로그
![image](https://user-images.githubusercontent.com/49313910/216231779-3f6300d6-62fc-432d-b2e5-3e8caa5e23dc.png)

- 기존에는 멤버와 주제를 묶는 멤버-주제 테이블이 있었습니다. 주제는 오늘의 문장을 결정하는 부분이고 해당 주제에 맞는 오늘의 문장을 어떤 멤버들이 갖는지가 더 맞는 것 같아 주제-오늘의 문장 ID를 FK로 갖는 멤버-주제-오늘의 문장으로 변경해주었습니다.

- 주제-스피킹 로그 테이블을 없애고 멤버-주제-오늘의 문장 ID 를 FK로 갖는 스피킹 로그로 변경하였습니다.

변경할 부분이 있다면 말씀해주세요!

**Comment by nathan29849** [comment]
굳 ! 너무 좋습니다!!

**Comment by HanKwanJin** [comment]
아! 다시 보니까 멤버가 선택한 주제를 알아야 오늘의 문장을 제공해줄 수 있어서 멤버-주제 테이블이 더 맞다는 생각이 갑자기 드는데 어떻게 생각하시나요?? 제가 바꾼 주제-오늘의 문장ID 는 멤버가 어떤 주제를 선택했는지 확인이 불가능할 것 같아서요!

**Comment by nathan29849** [comment]
말씀해주신 부분이 맞는 것 같아요
멤버-주제 테이블과 주제-오늘의 문장 테이블이 모두 존재해야 할 것 같습니다.

**Comment by HanKwanJin** [comment]
넵 다시 변경하겠습니다!

**Comment by HanKwanJin** [comment]
- [ ] 스터디 상세 조회에서와 스터디룸에서 댓글이 따로 존재하지 않아 StudyDetailResponse 에서 댓글 리스트를 제공하는 필드는 제거해야할 것 같습니다.

어떻게 생각하시나요?!

이슈 본문에 스터디 상세 부분 그림을 참고해주세요!

**Comment by nathan29849** [comment]
네 맞는 것 같아요!
그렇게 진행해주시면 될 것 같슴니당!!
